/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    notes: Note;
    subscribers: Subscriber;
    messages: Message;
    photos: Photo;
    clients: Client;
    people: Person;
    testimonials: Testimonial;
    papers: Paper;
    awards: Award;
    playground: Playground;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    projects: {
      testimonials: 'testimonials';
      notes: 'notes';
    };
    clients: {
      projects: 'projects';
    };
    people: {
      projects: 'projects';
    };
  };
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    papers: PapersSelect<false> | PapersSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    playground: PlaygroundSelect<false> | PlaygroundSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    about: About;
    pages: Page;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Used in the address, e.g. /work/noteai
   */
  slug: string;
  subtitle: string;
  code?: string | null;
  /**
   * e.g. 2025 or 2024 - 2026
   */
  year?: string | null;
  team?: string | null;
  /**
   * Who the work was for. The project then shows on that client's row on the Clients page.
   */
  client?: (number | null) | Client;
  /**
   * Show in the big carousel on the home page.
   */
  featured?: boolean | null;
  /**
   * Frame shown around the cover on the Work page. "none" shows the image edge to edge.
   */
  device?: ('phone' | 'tablet' | 'laptop' | 'none') | null;
  /**
   * Cover image or video. Leave empty to use the animated cover below.
   */
  image?: (number | null) | Media;
  /**
   * Animated cover used when there is no image.
   */
  cover?: ('voice' | 'grid' | 'doc' | 'stream' | 'market' | 'graph' | 'ledger' | 'fusion') | null;
  intro: string;
  /**
   * Optional italic note under the intro, e.g. who led the work.
   */
  credit?: string | null;
  /**
   * Each person is a persona from People: shown as an avatar with their name, role and link on hover.
   */
  teamMembers?: (number | Person)[] | null;
  /**
   * Quotes about this project, shown under the case study. Add them under People → Testimonials.
   */
  testimonials?: {
    docs?: (number | Testimonial)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Notes that mention this project. Set them on the note.
   */
  notes?: {
    docs?: (number | Note)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  services?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Blocks of text and media, top to bottom. Leave the heading and text empty for a media-only block, e.g. a hero video.
   */
  sections?:
    | {
        heading?: string | null;
        body?: string | null;
        /**
         * Laid out on a 12-column grid: items fill a row until their widths add up to full.
         */
        gallery?:
          | {
              source?: ('upload' | 'url' | 'placeholder') | null;
              width?: ('full' | 'twoThirds' | 'half' | 'third' | 'quarter') | null;
              /**
               * Shape of the frame.
               */
              aspect?: ('21/9' | '2/1' | '16/9' | '16/10' | '4/3' | '1/1' | '4/5' | '3/4' | '9/16') | null;
              /**
               * Image or video file.
               */
              image?: (number | null) | Media;
              /**
               * Image or video address. .mp4/.webm play as video; YouTube and Vimeo links are embedded.
               */
              url?: string | null;
              /**
               * Animated placeholder used when there is no file or link.
               */
              cover?: ('voice' | 'grid' | 'doc' | 'stream' | 'market' | 'graph' | 'ledger' | 'fusion') | null;
              fit?: ('cover' | 'contain') | null;
              /**
               * Panel behind the media.
               */
              background?: ('none' | 'dark' | 'light') | null;
              /**
               * Optional device chrome.
               */
              frame?: ('none' | 'browser' | 'phone') | null;
              caption?: string | null;
              /**
               * Starting count on the heart button shown on hover. 0 hides the count.
               */
              likes?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  note?: string | null;
  /**
   * Filters on the Clients page are built from these.
   */
  tags?: string[] | null;
  href?: string | null;
  /**
   * Optional. A light logo on a transparent background, used in the client strip on Home.
   */
  logo?: (number | null) | Media;
  /**
   * Set on each project's Card tab.
   */
  projects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  role?: string | null;
  /**
   * One or two lines, shown on the persona card when someone hovers the avatar on a project.
   */
  bio?: string | null;
  /**
   * Filters on the People page are built from these.
   */
  tags?: string[] | null;
  /**
   * LinkedIn or personal site. The avatar links here.
   */
  href?: string | null;
  /**
   * Square photo. Without one, a coloured monogram is drawn.
   */
  avatar?: (number | null) | Media;
  /**
   * Demo persona written as sample content. Replace or delete before launch.
   */
  demo?: boolean | null;
  /**
   * Projects this person is on. Set on each project's team.
   */
  projects?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  /**
   * e.g. Head of Product
   */
  role?: string | null;
  client?: (number | null) | Client;
  /**
   * Shows the quote on this case study too.
   */
  project?: (number | null) | Project;
  /**
   * Square photo. Without one, a coloured monogram is drawn.
   */
  avatar?: (number | null) | Media;
  /**
   * Marks a placeholder quote, shown with a Placeholder badge. Replace it with real words before launch.
   */
  demo?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title: string;
  /**
   * Used in the address, e.g. /notes/evals-before-features
   */
  slug: string;
  date: string;
  /**
   * One or two sentences for link previews and search engines.
   */
  summary?: string | null;
  /**
   * Optional. If set, the Notes list links to this address instead of the note page.
   */
  href?: string | null;
  /**
   * Optional image shown under the title.
   */
  cover?: (number | null) | Media;
  /**
   * Projects this note is about, shown as cards at the end of the note.
   */
  projects?: (number | Project)[] | null;
  /**
   * Headings, quotes, lists, links, images and videos. Use the + menu or type / to add blocks.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Passages readers highlighted, shown as dotted underlines. Readers add to this list; you can edit or remove any.
   */
  highlights?:
    | {
        text: string;
        count?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Readers' likes. Updated by the site.
   */
  likes?: number | null;
  /**
   * Page views. Updated by the site.
   */
  views?: number | null;
  year?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name?: string | null;
  email: string;
  subject?: string | null;
  message: string;
  /**
   * Tick once you've replied.
   */
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  image: number | Media;
  caption?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers".
 */
export interface Paper {
  id: number;
  title: string;
  venue?: string | null;
  year?: string | null;
  status?: string | null;
  href?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  where?: string | null;
  year?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playground".
 */
export interface Playground {
  id: number;
  title: string;
  body?: string | null;
  href?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'papers';
        value: number | Paper;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'playground';
        value: number | Playground;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  code?: T;
  year?: T;
  team?: T;
  client?: T;
  featured?: T;
  device?: T;
  image?: T;
  cover?: T;
  intro?: T;
  credit?: T;
  teamMembers?: T;
  testimonials?: T;
  notes?: T;
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        gallery?:
          | T
          | {
              source?: T;
              width?: T;
              aspect?: T;
              image?: T;
              url?: T;
              cover?: T;
              fit?: T;
              background?: T;
              frame?: T;
              caption?: T;
              likes?: T;
              id?: T;
            };
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  summary?: T;
  href?: T;
  cover?: T;
  projects?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        count?: T;
        id?: T;
      };
  likes?: T;
  views?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  note?: T;
  tags?: T;
  href?: T;
  logo?: T;
  projects?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  tags?: T;
  href?: T;
  avatar?: T;
  demo?: T;
  projects?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  client?: T;
  project?: T;
  avatar?: T;
  demo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "papers_select".
 */
export interface PapersSelect<T extends boolean = true> {
  title?: T;
  venue?: T;
  year?: T;
  status?: T;
  href?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  where?: T;
  year?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playground_select".
 */
export interface PlaygroundSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  email: string;
  city?: string | null;
  /**
   * Shown on Home and About.
   */
  portrait?: (number | null) | Media;
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A small green dot with the text beside it, in the header and on Home.
   */
  available?: boolean | null;
  availableText?: string | null;
  /**
   * The big headline at the top.
   */
  tagline: string;
  /**
   * Used as the site description for search and sharing.
   */
  intro?: string | null;
  aboutHeading?: string | null;
  aboutBody?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  approach?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Use a new line to break the heading.
   */
  contactHeading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heading: string;
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  contentVersion?: number | null;
  home?: {
    aboutLink?: string | null;
    approachTitle?: string | null;
    workTitle?: string | null;
    seeAllLabel?: string | null;
    clientsTitle?: string | null;
    testimonialsTitle?: string | null;
    /**
     * Numbers counted live from the CMS. Pick what to count and how to label it.
     */
    stats?:
      | {
          count: 'projects' | 'clients' | 'people' | 'notes' | 'papers' | 'awards';
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  work: {
    title: string;
    intro?: string | null;
    nextLabel?: string | null;
    clientLabel?: string | null;
    relatedNotesLabel?: string | null;
  };
  notes: {
    title: string;
    intro?: string | null;
    /**
     * Shown while there are no notes.
     */
    emptyText?: string | null;
    signupTitle?: string | null;
    signupText?: string | null;
    /**
     * Link to the RSS feed under the signup card.
     */
    rssLabel?: string | null;
    signedUpText?: string | null;
    allLabel?: string | null;
    nextLabel?: string | null;
    relatedLabel?: string | null;
  };
  photos: {
    title: string;
    intro?: string | null;
  };
  clients: {
    title: string;
    intro?: string | null;
    visitLabel?: string | null;
  };
  people: {
    title: string;
    intro?: string | null;
    projectsLabel?: string | null;
  };
  colophon: {
    title: string;
    intro?: string | null;
    rows?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  city?: T;
  portrait?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  available?: T;
  availableText?: T;
  tagline?: T;
  intro?: T;
  aboutHeading?: T;
  aboutBody?:
    | T
    | {
        text?: T;
        id?: T;
      };
  approach?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  contactHeading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heading?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  contentVersion?: T;
  home?:
    | T
    | {
        aboutLink?: T;
        approachTitle?: T;
        workTitle?: T;
        seeAllLabel?: T;
        clientsTitle?: T;
        testimonialsTitle?: T;
        stats?:
          | T
          | {
              count?: T;
              label?: T;
              id?: T;
            };
      };
  work?:
    | T
    | {
        title?: T;
        intro?: T;
        nextLabel?: T;
        clientLabel?: T;
        relatedNotesLabel?: T;
      };
  notes?:
    | T
    | {
        title?: T;
        intro?: T;
        emptyText?: T;
        signupTitle?: T;
        signupText?: T;
        rssLabel?: T;
        signedUpText?: T;
        allLabel?: T;
        nextLabel?: T;
        relatedLabel?: T;
      };
  photos?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  clients?:
    | T
    | {
        title?: T;
        intro?: T;
        visitLabel?: T;
      };
  people?:
    | T
    | {
        title?: T;
        intro?: T;
        projectsLabel?: T;
      };
  colophon?:
    | T
    | {
        title?: T;
        intro?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}